# Generated by Django 4.2.1 on 2023-06-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatergoriaProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DadosMeteorologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('temperatura', models.FloatField()),
                ('descricao', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('dataInicio', models.DateField(default=None, null=True)),
                ('dataFim', models.DateField(default=None, null=True)),
                ('detalhes', models.TextField(default='', max_length=5000)),
                ('pdfFile', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('alt', models.CharField(default='', max_length=255)),
                ('imagem', models.ImageField(upload_to='projetos/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('iframe', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricaoResumida', models.CharField(max_length=255)),
                ('descricao', models.TextField(max_length=5000)),
                ('destaqueHome', models.CharField(choices=[('1', 'Sim'), ('0', 'Não')], default='1', max_length=10)),
                ('categoria', models.ManyToManyField(related_name='projetos', to='portfolio.catergoriaprojeto')),
                ('fotos', models.ManyToManyField(related_name='projetos', to='portfolio.foto')),
            ],
        ),
    ]
