# Generated by Django 4.2.1 on 2023-06-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nomeItemMenu', models.CharField(default='', max_length=50)),
                ('seoTitle', models.CharField(default='', max_length=50)),
                ('seoDescription', models.TextField(default='', max_length=70)),
                ('html', models.TextField(default='')),
                ('posicao', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CatergoriaProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('alt', models.CharField(default='', max_length=255)),
                ('imagem', models.ImageField(upload_to='projetos/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('iframe', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricaoResumida', models.CharField(max_length=255)),
                ('descricao', models.TextField(max_length=5000)),
                ('destaqueHome', models.CharField(choices=[('1', 'Sim'), ('0', 'Não')], default='1', max_length=10)),
                ('categoria', models.ManyToManyField(related_name='projetos', to='portfolio.catergoriaprojeto')),
                ('fotos', models.ManyToManyField(related_name='projetos', to='portfolio.foto')),
            ],
        ),
    ]
