# Generated by Django 4.2.1 on 2023-06-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatergoriaProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='categoria',
            field=models.ManyToManyField(related_name='categorias', to='portfolio.catergoriaprojeto'),
        ),
    ]
