# Generated by Django 4.2.1 on 2023-06-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('dataInicio', models.DateField(default=None, null=True)),
                ('dataFim', models.DateField(default=None, null=True)),
                ('detalhes', models.TextField(default='', max_length=5000)),
                ('pdfFile', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
    ]
