# Generated by Django 4.2.1 on 2023-06-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_catergoriaprojeto_projeto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(max_length=5000),
        ),
    ]
