# Generated by Django 4.2.1 on 2023-06-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_formacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area_Site',
        ),
    ]
