# Generated by Django 4.2.1 on 2023-06-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_delete_area_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosMeteorologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('temperatura', models.FloatField()),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
    ]
