# Generated by Django 4.2.1 on 2023-06-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_projeto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='projetos/'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='categoria',
            field=models.ManyToManyField(related_name='projetos', to='portfolio.catergoriaprojeto'),
        ),
    ]
