# Generated by Django 4.2.1 on 2023-06-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projeto_imagem_alter_projeto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens/')),
            ],
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='imagem',
        ),
        migrations.AddField(
            model_name='projeto',
            name='fotos',
            field=models.ManyToManyField(related_name='projetos', to='portfolio.foto'),
        ),
    ]
