# Generated by Django 4.2.1 on 2023-06-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_dadosmeteorologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosmeteorologia',
            name='data_hora',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
