# Generated by Django 4.2.1 on 2023-06-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_foto_remove_projeto_imagem_projeto_fotos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foto',
            options={'verbose_name_plural': 'Fotos'},
        ),
        migrations.AddField(
            model_name='foto',
            name='alt',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='foto',
            name='imagem',
            field=models.ImageField(upload_to='imagens/projetos/'),
        ),
    ]
