# Generated by Django 4.2.1 on 2023-06-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_dadosmeteorologia_data_hora'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
