# Generated by Django 4.2.1 on 2023-06-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_foto_options_foto_alt_alter_foto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
