# Generated by Django 4.2.1 on 2023-06-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_foto_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foto',
            options={},
        ),
        migrations.AlterField(
            model_name='foto',
            name='imagem',
            field=models.ImageField(upload_to='projetos/'),
        ),
    ]
