# Generated by Django 4.2.1 on 2023-06-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='destaqueHome',
            field=models.CharField(choices=[('1', 'Sim'), ('0', 'Não')], default='1', max_length=10),
        ),
    ]
