# Generated by Django 4.2.1 on 2023-06-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_projeto_destaquehome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='area',
        ),
    ]
