# Generated by Django 4.2.1 on 2023-06-03 10:15

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_area_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('html', tinymce.models.HTMLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='areas',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Artigo',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
