# Generated by Django 4.2.1 on 2023-06-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_area_site_remove_artigo_areas_remove_artigo_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area_site',
            name='nomeItemMenu',
            field=models.CharField(default=models.CharField(max_length=50), max_length=50),
        ),
    ]
