# Generated by Django 4.2.1 on 2023-06-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_area_site_nomeitemmenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area_site',
            name='html',
        ),
    ]
