# Generated by Django 4.2.1 on 2023-06-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_area_site_posicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='area_site',
            name='seoDescription',
            field=models.TextField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='area_site',
            name='seoTitle',
            field=models.CharField(default='', max_length=50),
        ),
    ]
